{% set org = "openforcefield" %}
{% set name = "openff-qcsubmit" %}
{% set version = "0.59.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1
  
build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }},<3.15.0a0
    - numpy
    - tqdm
    - networkx
    - qcelemental >=0.50.2,<=0.51.2 # can relax later
    - qcportal >=0.65,<=0.70 # same
    - openff-toolkit-base >=0.12,<=0.19.0 # realistically the lower constraint should be much higher
    - openff-units >=0.4.0
    - rdkit
    - pyyaml
    - pydantic <3.0.0a0
    - basis_set_exchange
    - typing_extensions
    - mdtraj

test:
  requires:
    - python {{ python_min }}
  imports:
    - openff.qcsubmit
  files:
    - test_version_nonzero.py
  commands:
    - python test_version_nonzero.py

about:
  home: https://github.com/openforcefield/openff-qcsubmit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for submitting molecules to QCFractal
  description: |
    The OpenFF QCSubmit framework aims to facilitate curating and contributing
    new quantum chemical (QC) datasets to the QCArchive (or any other QCFractal instance),
    as well as to retrieve already computed datasets.
  doc_url: https://openff-qcsubmit.readthedocs.io
  dev_url: https://github.com/openforcefield/openff-qcsubmit

extra:
  recipe-maintainers:
    - JTHorton
    - SimonBoothroyd
    - j-wags
    - dotsdl
    - mattwthompson
